### PR TITLE
Entry page and sessions

### LINKED ISSUE #7: [Ian] User Sessions
We need users to be able to login and then be identified in their sessions.

### PR DESCRIPTION
**Pull request by aizon2456**
Trying to fix #7

### CODE REVIEW

**Comment by Rosengren** [comment]
A few comments
1. Why did you remove the password field in app/views/user/_form.html.erb
2. Why did you disable the user test cases?
3. We can remove the AddPasswordDigestToUser migration file and just add password_digest to the create_users migration file
4. The Users.yml fixture file should have "password_digest: MyString" where you removed the "password: MyString" line

**Comment by aizon2456** [comment]
1. Mistake, readded.
2. In theory, we are completely removing the default routing for the user, which will affect all test cases, not just the user's, as noted in #4 .
3. Made the change as requested by @Rosengren .
4. If readding the test cases, then yes this change should be made. @Rosengren has noted that this will be done in #5 .

**Comment by Rosengren** [comment]
Looks good!

**Comment by ntartania** [comment]
Have these changes been pushed to production? From the home page on Heroku I can't do anything.

**Comment by aizon2456** [comment]
We forgot to deploy to Heroku, and had to flush the database to remove old tables and update with the new schema. It should be updated now.

**Pull request merged**
